drop database if exists SJSUber;
create database SJSUber;
use SJSUber;

CREATE TABLE user(
	SJSU_ID		CHAR(9)			NOT NULL 	UNIQUE,
    EMAIL		VARCHAR(50) 	NOT NULL 	UNIQUE,
    USER_NAME	VARCHAR(25)		NOT NULL 	UNIQUE,
    ADDRESS		VARCHAR(50)		NOT NULL,
    NAME		VARCHAR(50)		NOT NULL,
    PASSWORD	VARCHAR(25)		NOT NULL,
    USER_TYPE	VARCHAR(10)		NOT NULL,
    ANSWER_SQ1	VARCHAR(50)		NOT NULL,
    ANSWER_SQ2	VARCHAR(50)		NOT NULL,
    PRIMARY KEY(SJSU_ID)
);

CREATE TABLE driver(
	LICENSE_NUM	CHAR(9)			NOT NULL	 	UNIQUE,
    SJID		CHAR(9)			NOT NULL,
    EXP_DATE	CHAR(8)			NOT NULL,
    PRIMARY KEY(LICENSE_NUM),
    FOREIGN KEY (SJID) REFERENCES user (SJSU_ID)
);

CREATE TABLE cars(
	LIC_NUM		CHAR(9)			NOT NULL		UNIQUE,
    REG_NUM		CHAR(9)			NOT NULL		UNIQUE,
    INSURANCE	VARCHAR(25)		NOT NULL,
	MAX_SEATS	CHAR(1)			NOT NULL,
	MODEL		VARCHAR(25)		NOT NULL,
	MAKE		VARCHAR(25)		NOT NULL,
    PRIMARY KEY(REG_NUM),
    FOREIGN KEY (LIC_NUM) REFERENCES driver (LICENSE_NUM)
);

CREATE TABLE route(
	ROUTE_ID	CHAR(9)			NOT NULL	 	UNIQUE,
    CREATED_ON	CHAR(10)		NOT NULL,
	DEPART_TIME	CHAR(8)			NOT NULL,
	SHORTEST_DIST	CHAR(2)		NOT NULL,
	START_LOC	VARCHAR(100)	NOT NULL,
	END_LOC		VARCHAR(100)	NOT NULL,
    PRIMARY KEY(ROUTE_ID)
);

CREATE TABLE stop(
	STOP_ID		CHAR(9)				NOT NULL	UNIQUE,
    PICKUP_LOC	VARCHAR(100)		NOT NULL,
	DROPOFF_LOC	VARCHAR(100)		NOT NULL,
	STOP_CREATED_ON	CHAR(10)		NOT NULL,
	STOP_DEPART_TIME CHAR(8)		NOT NULL,
    PRIMARY KEY(STOP_ID)
);

CREATE TABLE has2(
	RTE_ID		CHAR(9)			NOT NULL,
    STP_ID		CHAR(9)			NOT NULL,
	PRIMARY KEY (STP_ID),
    FOREIGN KEY (RTE_ID) REFERENCES	route	(ROUTE_ID),
	FOREIGN KEY	(STP_ID) REFERENCES	stop	(STOP_ID)
);

CREATE TABLE has1(
	L_NUM		CHAR(9)			NOT NULL,
    RTE_ID		CHAR(9)			NOT NULL,
    PRIMARY KEY (L_NUM),
    FOREIGN KEY (L_NUM)	REFERENCES	driver	(LICENSE_NUM),
	FOREIGN KEY	(RTE_ID) REFERENCES	route	(ROUTE_ID)
);


CREATE TABLE request(
	REQUEST_ID	CHAR(9)				NOT NULL	UNIQUE,
    SEATS_REQST	CHAR(1)				NOT NULL,
    DEPART_TIME	CHAR(8)				NOT NULL,
    CREATED_ON	CHAR(10)			NOT NULL,
    START_LOC	VARCHAR(100)		NOT NULL,
    END_LOC		VARCHAR(100)		NOT NULL,
    PRIMARY KEY	(REQUEST_ID)
);


CREATE TABLE makes(
	SJ_ID		CHAR(9)			NOT NULL,
    REQ_ID		CHAR(9)			NOT NULL,
    PRIMARY KEY	(SJ_ID),
    FOREIGN KEY	(SJ_ID)		REFERENCES user	(SJSU_ID),
    FOREIGN KEY	(REQ_ID)	REFERENCES request	(REQUEST_ID)
);

CREATE TABLE matches(
	RT_ID		CHAR(9)			NOT NULL,
    RQUST_ID	CHAR(9)			NOT NULL,
    ACCPT_REJ	CHAR(1),
    PRIMARY KEY	(RT_ID),
	FOREIGN KEY	(RT_ID)	REFERENCES	route	(ROUTE_ID),
    FOREIGN KEY	(RQUST_ID)	REFERENCES request	(REQUEST_ID)
);
